### ISSUE TITLE
Requests dependency 'urllib3' must be version >= 1.21.1, < 1.22!

### ISSUE THREAD

**Issue by oxidworks** [gtaylor/paypal-python#49]
Hi

Since today I can no longer import paypal in Python

LinuxMint 18
Python 2.7.12
paypal 1.2.5 (from pip)

```
>>> import paypal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paypal/__init__.py", line 3, in <module>
    from paypal.interface import PayPalInterface
  File "/usr/local/lib/python2.7/dist-packages/paypal/interface.py", line 13, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 61, in <module>
    raise RuntimeError('Requests dependency \'urllib3\' must be version >= 1.21.1, < 1.22!')
RuntimeError: Requests dependency 'urllib3' must be version >= 1.21.1, < 1.22!
```

Maybe I made an update yesterday, so I tried now to downgrade to 1.2.4 and 1.2.3 but the same error.
Also I was wonder why pip is version 1.2.5 and git 1.2.4

```
$ sudo -H pip search urllib3
urllib3 (1.21.1)             - HTTP library with thread-safe connection pooling, file post, and more.
  INSTALLED: 1.13.1
```

It runs now but only ich i change directory to /usr/local/lib/python2.7/dist-packages/paypal  and:
```
#linuxmint=1.13.1 #new=urllib3-1.21.1
$ sudo pip install urllib3 -t /usr/local/lib/python2.7/dist-packages/paypal 
#linuxmint=2.3.0 #new=chardet-3.0.4
$ sudo pip install chardet -t /usr/local/lib/python2.7/dist-packages/paypal  
```

regards

**Comment by gtaylor** [comment]
Explained in #50, but I don't see this is a paypal-python issue.
